### ISSUE TITLE
Terminal font size

### ISSUE THREAD

**Issue by jaemi** [learn-co/learn-ide-material-ui#4]
I can't seem to adjust the terminal font size. 

**Reproduction Steps:**

1. I added the style:
.script-view .line {
  font-size: 20px;
}
and saved my stylesheet.
2. Restarted the IDE
3. Console font is still tiny.

**Expected behavior:**

I expected the console font to get larger, based on what I found online in multiple places.

**Observed behavior:**

No matter which stylesheet I added this to, there was no change.

**Screenshots and GIFs**

![image](https://cloud.githubusercontent.com/assets/3371427/26480330/f1a9a656-418d-11e7-9c40-924041c9aee7.png)

**Atom version:** Learn IDE v2.4.2
**OS and version:** Windows 10 Creators update (10.0.15063)

**Installed packages:**

Whatever came with the IDE.

**Comment by davo-99** [comment]
Can you tell me how do I go to my editor stylesheet and put that code there as well?
